version: "3"

services:

  parser: &base
    image: zabbix-confirm-accident:0.1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: main-parser.py
    env_file:
      - ".env"
    volumes:
      - "outages:/app/outages"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  consumer:
    <<: *base
    command: consumer.py
    restart: always
    extra_hosts:
      - "${EXTRA_HOST}"
    volumes:
      - "outages:/app/outages"
      - "./certs:/app/certs:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      RABBITMQ_CACERT: "/app/certs/root.crt"
      RABBITMQ_CERTFILE: "/app/certs/client.crt"
      RABBITMQ_KEYFILE: "/app/certs/client.key"
    env_file:
      - ".env"

volumes:
  outages:
