import re
from typing import Tuple

dr_dict = {
    "Aktybinsk": "ул. Актюбинская",
    "Aktyubinsk": "ул. Актюбинская",
    "Gorpisw": "ул. Горпищенко",
    "Pobedi": "пр-кт Победы",
    "GO": "пр-кт Генерала Острякова",
    "Balt": "ул. Балтийская",
    "Dionis": "СТ Дионис",
    "GOstryak": "пр-кт Генерала Острякова",
    "Hrust": "ул. Хрусталева",
    "Industr": "ул. Индустриальная",
    "Kamysh": "Камышовое шоссе",
    "Rudn": "ул. Руднева",
    "Solov": "ул. Соловьёва",
    "Tokar": "ул. Токарева",
    "Ugolnaya": "ул. Угольная",
    "Koshev": "ул. Олега Кошевого",
    "Musyk": "ул. Николая Музыки",
    "BMorsk": "ул. Большая Морская",
    "Lenin": "ул. Ленина",
    "AdOkt": "ул. Адмирала Октябрьского",
    "Gogol": "ул. Гоголя",
    "Ochak": "ул. Очаковцев",
    "GP": "ул. Генерала Петрова",
    "6Bastion": "ул. 6-я Бастионная",
    "GPetrova": "ул. Генерала Петрова",
    "Karant": "ул. Карантинная",
    "Kommun": "ул. Коммунистическая",
    "Pozhar": "ул. Пожарова",
    "Safron": "ул. Сафронова",
    "Tolstogo": "ул. Льва Толстого",
    "Vakulenchuka": "ул. Вакуленчука",
    "Vakulench": "ул. Вакуленчука",
    "Mensh": "ул. Меньшикова",
    "Repin": "ул. Репина",
    "Tulsk": "ул. Тульская",
    "Gluh": "ул. Глухова",
    "LChayk": "ул. Лизы Чайкиной",
    "Sladk": "ул. Сладкова",
    "GStalingr": "пр- кт Героев Сталинграда",
    "Antichn": "ул. Античный",
    "GBrest": "ул. Героев Бреста",
    "Kesaev": "ул. Астана Кесаева",
    "Mayach": "ул. Маячная",
    "POR": "ул. Октябрьской Революции",
    "Shevchenko": "ул. Шевченко",
    "Fiolent": "Фиолентовское шоссе",
    "KPotap": "ул. Комбрига Потапова",
    "Marines": "ул. Александра Маринеско",
    "Shevch": "ул. Тараса Шевченко",
    "HutLukomsk": "ул. Лукомская",
    "Kosareva": "ул. Косарева",
    "Kosar": "ул. Косарева",
    "MolStroy": "ул. Молодых Строителей",
    "Stepan": "ул. Степаняна",
    "Krestovskogo": "ул. Крестовского",
    "Aksut": "ул. Аксютина",
    "Drapushko": "ул. Драпушко",
    "Fizkult": "ул. Физкультурная",
    "Krestovsk": "ул. Крестовского",
    "Mira": "ул. Мира",
    "Nevsk": "ул. Невская",
    "Novik": "ул. Новикова",
    "perFiz": "пер. Физкультурный",
    "Raket": "ул. Ракетная",
    "Solnech": "ул. Солнечная",
    "Kolob": "ул. Колобова",
    "Fiol": "Фиолентовское шоссе",
    "Kolobova": "ул. Колобова",
    "Stolet": "пр-кт Столетовский",
    "Raenko": "ул. Раенко",
    "Primorsk": "ул. Приморская",
    "BKazachia": "ул. Казачья",
    "Ryb": "СТ Рыбак",
    "Saturn": "СТ Сатурн",
    "ZBbKamish": "Западный берег Камышовой бухты",
    "Ahtiar": "СТ Ахтиар",
    "bKazachya": "ул. Казачья",
    "Ligovsk": "ул.Лиговская",
    "Pilot_Sev": "СТ Пилот",
    "Vodok": "СТ Водоканал-2",
    "Fadeeva": "ул. Адмирала Фадеева",
    "Fiolentov": "Фиолентовское шоссе",
    "Otradn": "ул. Отрадная",
    "Parkov": "ул. Парковая",
    "Shitov": "ул. Щитовая",
    "Korchag": "ул. Павла Корчагина",
    "Ribakov": "ул. Рыбаков",
    "Bluher": "ул. Маршала Блюхера",
    "BMihail": "ул. Бориса Михайлова",
    "MarKril": "ул. Маршала Крылова",
    "Pravd": "ул. Правды",
    "Proletar": "ул. Пролетарская",
    "Proletarskaya": "ул. Пролетарская",
    "Chelnok": "ул. Челнокова",
    "GSev": "ул. Героев Севастополя",
    "Istomin": "ул. Истомина",
    "Mihailovskaya": "ул. Михайловская",
    "Buryaka": "ул. Буряка",
    "Gromov": "ул. Громова",
    "Gvardeisk": "ул. Гвардейская",
    "Machtov": "ул. Мачтовая",
    "Mihaylovs": "ул. Михайловская",
    "Simonka": "ул. Симонка",
    "Simonok": "ул. Симонка",
    "SosnR": "СТ Сосновая роща",
    "SrednProezd": "проезд Средний",
    "Yakornaya": "ул. Якорная",
    "VoenStroit": "ул. Военных строителей",
    "perRubeg": "пер. Рубежный",
    "Pilot_Mys": "СТ Пилот",
    "Pilot_UG": "СТ Пилот",
    "Vstroitel": "ул. Военных строителей",
    "GPodvodnikov": "ул. Героев Подводников",
    "50let": "50-летия СССР",
    "DmUlyan": "ул. Дмитрия Ульянова",
    "Drevn": "ул. Древняя",
    "Dybenko": "ул. Павла Дыбенко",
    "Erosh": "ул. Ерошенко",
    "Gagarina": "пр-кт Гагарина",
    "NOstrovs": "ул. Надежды Островской",
    "Podvodn": "ул. Героев Подводников",
    "Shostaka": "ул. Шостака",
    "Vakul": "ул. Вакуленчука",
    "Gorpischenko": "ул. Горпищенко",
    "Gorpish": "ул. Горпищенко",
    "Semipalat": "ул. Семипалатинская",
    "Pobedy": "пр-кт Победы",
    "Melnika": "ул. Генерала Мельника",
    "Gelovani": "ул. Геловани",
    #"RELE": " ",
    "Izumrud": "Изумруд",
    "LASPI": "Ласпи",
    "SZ_YUBK": "Севастопольская зона ЮБК",
    "IzumrudAdm": "Изумруд",
    #"Andreevka": "с. Андреевка",
    #"Solnechniy": "п. Солнечный",
    "Centralnaya": "ул. Центральная",
    "Nevskaya": "ул. Невская",
    #"Gollandia": " ",
    "Blyuhera": "ул. Маршала Блюхера",
    "Flagman": "ул. Флагманская",
    "MaksDacha": " ",
    "Kalicha": "ул. Калича",
    "Stroitelnaya": "ул. Строительная",
    #"Ternovka": " ",
    "Rabochaya": "Рабочая",
    "Korabelnaya": "ул. Корабельная",
    "Zhidilova": "ул. Генерала Жидилова",
    "Makarova": "ул. Адмирала Макарова",
    #"Orlinoe": " ",
    "Kedrovaya": "ул. Кедровая",
    "Pahomova": "ул. Ивана Пахомова",
    "Smotrovaya": "Смотровая площадка",
    "Volodarskogo": "ул. Володарского",
    "Popova": "ул. Попова",
    "Sovetskaya": "ул. Советская",
    #"Kacha": " ",
    "Aviat": "ул. Авиаторов",
    #"Komendat": " ",
    "Krasnoar": "ул. Красноармейская",
    "Nesterova": "ул. Нестерова",
    "Parusk": "Отель Парус",
    #"Orlovka": " ",
    #"Belbek": " ",
    "KachinskoeShosse": "Качинское шоссе",
    #"Lyubimovka": " ",
    "Shkolnaya": "ул. Школьная",
    "VyazRoscha": "Вязовая роща",
    "STBereg": "СТ Берег",
    #"Vavilovo": " ",
    "Parshina": "ул. Паршина",
    #"Verhnesadovoe": " ",
    #"VerhnesadovoeAdm": " ",
    #"VerhnesadovoeBiblioteka": " ",
    "Bogdanova": "ул. Богданова",
    #"BogdMarket": " ",
    #"SahGolovka": " ",
    "Angarskaya": "ул.Ангарская",
    #"GRES": " ",
    "Shubikova": "ул. Шубикова",
    "Timiryazeva": "ул. Тимирязева",
    "Tolbuhina": "ул. Толбухина",
    "Odesskaya": "ул. Одесская",
    "GStal": "пр-кт Героев Сталинграда",
    "OMEGA": "Омега",
    "ParkPobedy": "Парк Победы",
    "Yumasheva": "ул. Юмашева",
    #"Akvamarin": " ",
    "NOstr": "ул. Надежды Островской",
    #"AhmatovaPark": " ",
    "DUlyanova": "ул. Дмитрия Ульянова",
    "Efremova": "ул. Ефремова",
    "Eroshenko": "ул. Ерошенко",
    "FiolentSh": "Фиолентовское шоссе",
    "LChaikinoi": "ул. Лизы Чайкиной",
    "Menshikova": "ул. Меньшикова",
    "Repina": "ул. Репина",
    "Universitet": "ул. Университетская",
    "Konduktor": "ул. Кондукторская",
    "Ohotskaya": "ул. Охотская",
    #"10KM": "",
    "Dneprovskaya": "ул. Днепровская",
    "GOstryakova": "пр-кт Генерала Омтрякова",
    "Hrustaleva": "ул. Хрусталёва",
    "Kievskaya": "ул. Киевская",
    #"Sevenergo": " ",
    "Silaeva": "ул. Силаева",
    "Gasforta": "Гасфорта",
    "Ind": "ул. Индустриальная",
}


def get_info_from_zabbix_node(name: str) -> Tuple[str, str]:
    """

    :param name:
    :return:
    """

    # позже будет возвращать улицу, дом и корпус
    #name = name.split("\n")
    res = []
    street_zabbix = ""
    house_zabbix = ""
    korpus_zabbix = ""

    match = re.search(
        r"(?:SVSL|FTTB|MSAN)[-_](?:\d+[-_])?(\d{0,2}[a-z_A-Z]+)(\d+[abvwgdeABVWGDE.\d]{0,2})?(k\d{1,2})?\S*", name)
    if match:
        res.append(match.groups())
        # тут разделение на все 3 интересующие нас группы улицу, дом и корпус
        street_zabbix = match.group(1)
        house_zabbix = match.group(2)
        korpus_zabbix = match.group(3)

        if korpus_zabbix == None:
            korpus_zabbix = ""

    return dr_dict.get(street_zabbix), f"{house_zabbix+korpus_zabbix}"
